package com.ober.core.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.autoid
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.name
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.account
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.type
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.branch_code
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    private String branchCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.autoid
     *
     * @return the value of tb_user.autoid
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.autoid
     *
     * @param autoid the value for tb_user.autoid
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.name
     *
     * @return the value of tb_user.name
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.name
     *
     * @param name the value for tb_user.name
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.account
     *
     * @return the value of tb_user.account
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.account
     *
     * @param account the value for tb_user.account
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.type
     *
     * @return the value of tb_user.type
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.type
     *
     * @param type the value for tb_user.type
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.branch_code
     *
     * @return the value of tb_user.branch_code
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.branch_code
     *
     * @param branchCode the value for tb_user.branch_code
     *
     * @mbggenerated Tue Aug 22 10:02:38 CST 2017
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode == null ? null : branchCode.trim();
    }
}